//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIMoviles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subastas
    {
        public Subastas()
        {
            this.Pujas = new HashSet<Pujas>();
        }
    
        public int idSubasta { get; set; }
        public int idDispositivo { get; set; }
        public decimal precioInicial { get; set; }
        public System.DateTime fin { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
        public virtual ICollection<Pujas> Pujas { get; set; }
    }
}
